name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # For a static site, skip npm install/build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          # Use the exact secret name the CLI created for you.
          # From your earlier output it looked like:
          #   FIREBASE_SERVICE_ACCOUNT_SPLITTY_C4BA4
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPLITTY_C4BA4 }}"
          channelId: live
          projectId: splitty-c4b4a
